"""update db

Revision ID: 0e5bcd6cd911
Revises: c2a3587c02ac
Create Date: 2026-04-08 22:36:22.103758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e5bcd6cd911"
down_revision: Union[str, Sequence[str], None] = "c2a3587c02ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nhan_vien_phong_ban",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("nhan_vien_id", sa.String(length=32), nullable=False),
        sa.Column("phong_ban_id", sa.String(length=32), nullable=False),
        sa.Column("ngay_bat_dau", sa.DateTime(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["nhan_vien_id"], ["nhan_vien.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["phong_ban_id"], ["phong_ban.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Drop FK constraints before dropping table
    op.drop_constraint(
        op.f("nhan_vien_trinh_do_id_fkey"), "nhan_vien", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("nhan_vien_phong_ban_id_fkey"), "nhan_vien", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("nhan_vien_chuc_vu_id_fkey"), "nhan_vien", type_="foreignkey"
    )
    # Now safe to drop table
    op.drop_table("trinh_do")
    op.add_column("chuc_vu", sa.Column("cap_bac", sa.Integer(), nullable=False))
    op.add_column("chuc_vu", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("nhan_vien", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_column("nhan_vien", "phong_ban_id")
    op.drop_column("nhan_vien", "chuc_vu_id")
    op.drop_column("nhan_vien", "trinh_do_id")
    op.add_column("phong_ban", sa.Column("cha_id", sa.String(length=32), nullable=True))
    op.add_column("phong_ban", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_foreign_key(
        None, "phong_ban", "phong_ban", ["cha_id"], ["id"], ondelete="SET NULL"
    )
    op.execute(
        "ALTER TABLE tai_khoan DROP CONSTRAINT IF EXISTS tai_khoan_ma_kich_hoat_key"
    )
    for col in [
        "ma_kich_hoat",
        "da_kich_hoat",
        "cuoc_dang_nhap_cuoi",
        "het_han_mat_khau",
        "so_lan_dang_nhap_that_bai",
        "ly_do_khoa",
        "bi_khoa",
    ]:
        op.execute(f"ALTER TABLE tai_khoan DROP COLUMN IF EXISTS {col}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tai_khoan",
        sa.Column(
            "bi_khoa",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tai_khoan",
        sa.Column(
            "ly_do_khoa", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "tai_khoan",
        sa.Column(
            "so_lan_dang_nhap_that_bai",
            sa.SMALLINT(),
            server_default=sa.text("'0'::smallint"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tai_khoan",
        sa.Column("het_han_mat_khau", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tai_khoan",
        sa.Column(
            "cuoc_dang_nhap_cuoi",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tai_khoan",
        sa.Column(
            "da_kich_hoat",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tai_khoan",
        sa.Column(
            "ma_kich_hoat", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint(
        op.f("tai_khoan_ma_kich_hoat_key"),
        "tai_khoan",
        ["ma_kich_hoat"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "phong_ban", type_="foreignkey")
    op.drop_column("phong_ban", "deleted_at")
    op.drop_column("phong_ban", "cha_id")
    op.add_column(
        "nhan_vien",
        sa.Column(
            "trinh_do_id", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "nhan_vien",
        sa.Column(
            "chuc_vu_id", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "nhan_vien",
        sa.Column(
            "phong_ban_id", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("nhan_vien_trinh_do_id_fkey"),
        "nhan_vien",
        "trinh_do",
        ["trinh_do_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("nhan_vien_phong_ban_id_fkey"),
        "nhan_vien",
        "phong_ban",
        ["phong_ban_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("nhan_vien_chuc_vu_id_fkey"),
        "nhan_vien",
        "chuc_vu",
        ["chuc_vu_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("nhan_vien", "deleted_at")
    op.drop_column("chuc_vu", "deleted_at")
    op.drop_column("chuc_vu", "cap_bac")
    op.create_table(
        "trinh_do",
        sa.Column("id", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "ma_trinh_do", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "ten_trinh_do", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("cap_do", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("mo_ta", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("trang_thai", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("trinh_do_pkey")),
        sa.UniqueConstraint(
            "ma_trinh_do",
            name=op.f("trinh_do_ma_trinh_do_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("nhan_vien_phong_ban")
    # ### end Alembic commands ###
