"""add_don_xin_nghi_so_ngay_phep_cham_cong

Revision ID: 519a9fd83f52
Revises: rename_datetime_columns
Create Date: 2026-04-13 12:49:42.437364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '519a9fd83f52'
down_revision: Union[str, Sequence[str], None] = 'rename_datetime_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cau_hinh_he_thong_luong', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('cau_hinh_he_thong_luong', 'trang_thai',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('cau_hinh_he_thong_luong', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_cau_hinh_luong_ngay'), table_name='cau_hinh_he_thong_luong')
    op.alter_column('cau_hinh_thuong_tet', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('cau_hinh_thuong_tet', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.add_column('chi_tiet_khau_tru', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('chi_tiet_khau_tru', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'tra_luong_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'loai_khau_tru',
               existing_type=sa.CHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'ten_khau_tru',
               existing_type=sa.CHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_constraint(op.f('chi_tiet_khau_tru_tra_luong_id_fkey'), 'chi_tiet_khau_tru', type_='foreignkey')
    op.drop_column('chi_tiet_khau_tru', 'ngay_tao')
    op.add_column('chi_tiet_phu_cap', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('chi_tiet_phu_cap', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'tra_luong_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'loai_phu_cap',
               existing_type=sa.CHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'ten_phu_cap',
               existing_type=sa.CHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_constraint(op.f('chi_tiet_phu_cap_tra_luong_id_fkey'), 'chi_tiet_phu_cap', type_='foreignkey')
    op.drop_column('chi_tiet_phu_cap', 'ngay_tao')
    op.alter_column('he_so_luong_danh_muc', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'ma_ngach',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'ten_ngach',
               existing_type=sa.CHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'cap_hoc',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_he_so_luong_ma_ngach'), table_name='he_so_luong_danh_muc')
    op.alter_column('ky_luat_vien_chuc', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'nhan_vien_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'hinh_thuc',
               existing_type=sa.CHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'muc_do_vi_pham',
               existing_type=sa.CHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('ky_luat_vien_chuc', 'trang_thai',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'nguoi_ky',
               existing_type=sa.CHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ky_luat_vien_chuc', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_ky_luat_nhan_vien'), table_name='ky_luat_vien_chuc')
    op.drop_constraint(op.f('ky_luat_vien_chuc_nhan_vien_id_fkey'), 'ky_luat_vien_chuc', type_='foreignkey')
    op.alter_column('ky_luong', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('ky_luong', 'trang_thai',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('ky_luong', 'nguoi_duyet',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('ky_luong', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_ky_luong_thang_nam'), table_name='ky_luong')
    op.alter_column('luong', 'ma_ngach',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('luong', 'phu_cap_tham_nien_vuot_khung',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('luong_thang_13', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('luong_thang_13', 'nhan_vien_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('luong_thang_13', 'trang_thai',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('luong_thang_13', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_constraint(op.f('luong_thang_13_nhan_vien_id_fkey'), 'luong_thang_13', type_='foreignkey')
    op.drop_column('nhan_vien', 'ngay_vao_nganh')
    op.create_index(op.f('ix_nhan_vien_cong_tac_chuc_vu_id'), 'nhan_vien_cong_tac', ['chuc_vu_id'], unique=False)
    op.create_index(op.f('ix_nhan_vien_cong_tac_nhan_vien_id'), 'nhan_vien_cong_tac', ['nhan_vien_id'], unique=False)
    op.create_index(op.f('ix_nhan_vien_cong_tac_phong_ban_id'), 'nhan_vien_cong_tac', ['phong_ban_id'], unique=False)
    op.alter_column('phu_cap_theo_cap_hoc', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('phu_cap_theo_cap_hoc', 'cap_hoc',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('phu_cap_theo_cap_hoc', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tam_dinh_chi_cong_tac', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('tam_dinh_chi_cong_tac', 'nhan_vien_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('tam_dinh_chi_cong_tac', 'quyet_dinh_so',
               existing_type=sa.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tam_dinh_chi_cong_tac', 'nguoi_tao',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_tam_dinh_chi_nhan_vien'), table_name='tam_dinh_chi_cong_tac')
    op.drop_constraint(op.f('tam_dinh_chi_cong_tac_nhan_vien_id_fkey'), 'tam_dinh_chi_cong_tac', type_='foreignkey')
    op.add_column('tra_luong', sa.Column('phu_cap_chuc_vu', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('phu_cap_tham_nien', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('phu_cap_uu_dai', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('phu_cap_khu_vuc', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('phu_cap_tham_nien_vuot_khung', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('phu_cap_khac', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('bhxh', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('bhyt', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('bhtn', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('thue_tncn', sa.BigInteger(), nullable=False))
    op.add_column('tra_luong', sa.Column('khau_tru_khac', sa.BigInteger(), nullable=False))
    op.alter_column('tra_luong', 'ky_luong_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tra_luong', 'loai_cong_thuc',
               existing_type=sa.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('tra_luong', 'tam_dinh_chi_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tra_luong', 'ky_luat_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.create_foreign_key(None, 'tra_luong', 'ky_luong', ['ky_luong_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tra_luong', type_='foreignkey')
    op.alter_column('tra_luong', 'ky_luat_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('tra_luong', 'tam_dinh_chi_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('tra_luong', 'loai_cong_thuc',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=10),
               existing_nullable=True)
    op.alter_column('tra_luong', 'ky_luong_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.drop_column('tra_luong', 'khau_tru_khac')
    op.drop_column('tra_luong', 'thue_tncn')
    op.drop_column('tra_luong', 'bhtn')
    op.drop_column('tra_luong', 'bhyt')
    op.drop_column('tra_luong', 'bhxh')
    op.drop_column('tra_luong', 'phu_cap_khac')
    op.drop_column('tra_luong', 'phu_cap_tham_nien_vuot_khung')
    op.drop_column('tra_luong', 'phu_cap_khu_vuc')
    op.drop_column('tra_luong', 'phu_cap_uu_dai')
    op.drop_column('tra_luong', 'phu_cap_tham_nien')
    op.drop_column('tra_luong', 'phu_cap_chuc_vu')
    op.create_foreign_key(op.f('tam_dinh_chi_cong_tac_nhan_vien_id_fkey'), 'tam_dinh_chi_cong_tac', 'nhan_vien', ['nhan_vien_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tam_dinh_chi_nhan_vien'), 'tam_dinh_chi_cong_tac', ['nhan_vien_id'], unique=False)
    op.alter_column('tam_dinh_chi_cong_tac', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('tam_dinh_chi_cong_tac', 'quyet_dinh_so',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('tam_dinh_chi_cong_tac', 'nhan_vien_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('tam_dinh_chi_cong_tac', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('phu_cap_theo_cap_hoc', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('phu_cap_theo_cap_hoc', 'cap_hoc',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('phu_cap_theo_cap_hoc', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_nhan_vien_cong_tac_phong_ban_id'), table_name='nhan_vien_cong_tac')
    op.drop_index(op.f('ix_nhan_vien_cong_tac_nhan_vien_id'), table_name='nhan_vien_cong_tac')
    op.drop_index(op.f('ix_nhan_vien_cong_tac_chuc_vu_id'), table_name='nhan_vien_cong_tac')
    op.add_column('nhan_vien', sa.Column('ngay_vao_nganh', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('luong_thang_13_nhan_vien_id_fkey'), 'luong_thang_13', 'nhan_vien', ['nhan_vien_id'], ['id'], ondelete='CASCADE')
    op.alter_column('luong_thang_13', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('luong_thang_13', 'trang_thai',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('luong_thang_13', 'nhan_vien_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('luong_thang_13', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('luong', 'phu_cap_tham_nien_vuot_khung',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('luong', 'ma_ngach',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_ky_luong_thang_nam'), 'ky_luong', ['thang', 'nam'], unique=False)
    op.alter_column('ky_luong', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('ky_luong', 'nguoi_duyet',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('ky_luong', 'trang_thai',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('ky_luong', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.create_foreign_key(op.f('ky_luat_vien_chuc_nhan_vien_id_fkey'), 'ky_luat_vien_chuc', 'nhan_vien', ['nhan_vien_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ky_luat_nhan_vien'), 'ky_luat_vien_chuc', ['nhan_vien_id'], unique=False)
    op.alter_column('ky_luat_vien_chuc', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('ky_luat_vien_chuc', 'nguoi_ky',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=100),
               existing_nullable=True)
    op.alter_column('ky_luat_vien_chuc', 'trang_thai',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'muc_do_vi_pham',
               existing_type=sa.String(length=30),
               type_=sa.CHAR(length=30),
               existing_nullable=True)
    op.alter_column('ky_luat_vien_chuc', 'hinh_thuc',
               existing_type=sa.String(length=30),
               type_=sa.CHAR(length=30),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'nhan_vien_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('ky_luat_vien_chuc', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_he_so_luong_ma_ngach'), 'he_so_luong_danh_muc', ['ma_ngach'], unique=False)
    op.alter_column('he_so_luong_danh_muc', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('he_so_luong_danh_muc', 'cap_hoc',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'ten_ngach',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=100),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'ma_ngach',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('he_so_luong_danh_muc', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.add_column('chi_tiet_phu_cap', sa.Column('ngay_tao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chi_tiet_phu_cap_tra_luong_id_fkey'), 'chi_tiet_phu_cap', 'tra_luong', ['tra_luong_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chi_tiet_phu_cap', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('chi_tiet_phu_cap', 'ten_phu_cap',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=100),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'loai_phu_cap',
               existing_type=sa.String(length=30),
               type_=sa.CHAR(length=30),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'tra_luong_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('chi_tiet_phu_cap', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('chi_tiet_phu_cap', 'created_at')
    op.add_column('chi_tiet_khau_tru', sa.Column('ngay_tao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chi_tiet_khau_tru_tra_luong_id_fkey'), 'chi_tiet_khau_tru', 'tra_luong', ['tra_luong_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chi_tiet_khau_tru', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('chi_tiet_khau_tru', 'ten_khau_tru',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=100),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'loai_khau_tru',
               existing_type=sa.String(length=30),
               type_=sa.CHAR(length=30),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'tra_luong_id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('chi_tiet_khau_tru', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('chi_tiet_khau_tru', 'created_at')
    op.alter_column('cau_hinh_thuong_tet', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('cau_hinh_thuong_tet', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_cau_hinh_luong_ngay'), 'cau_hinh_he_thong_luong', ['ngay_ap_dung'], unique=False)
    op.alter_column('cau_hinh_he_thong_luong', 'nguoi_tao',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('cau_hinh_he_thong_luong', 'trang_thai',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('cau_hinh_he_thong_luong', 'id',
               existing_type=sa.String(length=32),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
