"""refactor_nhan_vien_cong_tac_table

Revision ID: ac9225a0a31e
Revises: be7217d5263d
Create Date: 2026-04-09 00:16:26.176376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac9225a0a31e'
down_revision: Union[str, Sequence[str], None] = 'be7217d5263d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nhan_vien_cong_tac',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('phong_ban_id', sa.String(length=32), nullable=False),
    sa.Column('chuc_vu_id', sa.String(length=32), nullable=False),
    sa.Column('ngay_bat_dau', sa.DateTime(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.DateTime(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('he_so_luong', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chuc_vu_id'], ['chuc_vu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phong_ban_id'], ['phong_ban.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nhan_vien_phong_ban')
    op.drop_constraint(op.f('nhan_vien_chuc_vu_id_fkey'), 'nhan_vien', type_='foreignkey')
    op.drop_column('nhan_vien', 'chuc_vu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nhan_vien', sa.Column('chuc_vu_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('nhan_vien_chuc_vu_id_fkey'), 'nhan_vien', 'chuc_vu', ['chuc_vu_id'], ['id'])
    op.create_table('nhan_vien_phong_ban',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('nhan_vien_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('phong_ban_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('ngay_bat_dau', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], name=op.f('nhan_vien_phong_ban_nhan_vien_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phong_ban_id'], ['phong_ban.id'], name=op.f('nhan_vien_phong_ban_phong_ban_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nhan_vien_phong_ban_pkey'))
    )
    op.drop_table('nhan_vien_cong_tac')
    # ### end Alembic commands ###
