"""add_chuc_vu_fk_to_nhan_vien

Revision ID: be7217d5263d
Revises: 0e5bcd6cd911
Create Date: 2026-04-09 00:12:47.846630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7217d5263d'
down_revision: Union[str, Sequence[str], None] = '0e5bcd6cd911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nhan_vien', sa.Column('chuc_vu_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'nhan_vien', 'chuc_vu', ['chuc_vu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nhan_vien', type_='foreignkey')
    op.drop_column('nhan_vien', 'chuc_vu_id')
    # ### end Alembic commands ###
