"""create tables

Revision ID: c2a3587c02ac
Revises: 
Create Date: 2026-04-05 18:36:19.410366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a3587c02ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chuc_vu',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ma_chuc_vu', sa.String(length=20), nullable=False),
    sa.Column('ten_chuc_vu', sa.String(length=100), nullable=False),
    sa.Column('he_so_phu_cap', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('tieu_chuan', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_chuc_vu')
    )
    op.create_table('phong_ban',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ma_phong_ban', sa.String(length=20), nullable=False),
    sa.Column('ten_phong_ban', sa.String(length=100), nullable=False),
    sa.Column('loai', sa.String(length=20), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('truong_phong', sa.String(length=100), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_phong_ban')
    )
    op.create_table('trinh_do',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ma_trinh_do', sa.String(length=20), nullable=False),
    sa.Column('ten_trinh_do', sa.String(length=100), nullable=False),
    sa.Column('cap_do', sa.SmallInteger(), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_trinh_do')
    )
    op.create_table('nhan_vien',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ma_nhan_vien', sa.String(length=20), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('gioi_tinh', sa.String(length=5), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('que_quan', sa.String(length=200), nullable=True),
    sa.Column('dia_chi_thuong_tru', sa.String(length=255), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('so_cccd', sa.String(length=12), nullable=True),
    sa.Column('anh_dai_dien', sa.String(length=500), nullable=True),
    sa.Column('loai_nhan_vien', sa.String(length=20), nullable=False),
    sa.Column('mon_day', sa.String(length=100), nullable=True),
    sa.Column('hang_chuc_danh', sa.String(length=50), nullable=True),
    sa.Column('phong_ban_id', sa.String(length=32), nullable=True),
    sa.Column('chuc_vu_id', sa.String(length=32), nullable=True),
    sa.Column('trinh_do_id', sa.String(length=32), nullable=True),
    sa.Column('loai_hop_dong', sa.String(length=30), nullable=False),
    sa.Column('so_hop_dong', sa.String(length=50), nullable=True),
    sa.Column('ngay_vao_lam', sa.Date(), nullable=True),
    sa.Column('ngay_het_hop_dong', sa.Date(), nullable=True),
    sa.Column('la_dang_vien', sa.Boolean(), nullable=False),
    sa.Column('la_doan_vien', sa.Boolean(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chuc_vu_id'], ['chuc_vu.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phong_ban_id'], ['phong_ban.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trinh_do_id'], ['trinh_do.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ma_nhan_vien'),
    sa.UniqueConstraint('so_cccd')
    )
    op.create_table('bang_cap_chung_chi',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('loai', sa.String(length=30), nullable=False),
    sa.Column('ten_bang', sa.String(length=200), nullable=False),
    sa.Column('chuyen_nganh', sa.String(length=100), nullable=True),
    sa.Column('truong_cap', sa.String(length=200), nullable=True),
    sa.Column('nam_cap', sa.SmallInteger(), nullable=True),
    sa.Column('xep_loai', sa.String(length=20), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cham_cong',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('thang', sa.SmallInteger(), nullable=False),
    sa.Column('nam', sa.SmallInteger(), nullable=False),
    sa.Column('so_ngay_lam_chuan', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('so_ngay_lam_thuc_te', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('so_ngay_nghi_phep', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('so_ngay_nghi_om', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('so_ngay_cong_tac', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('so_ngay_nghi_khong_phep', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('so_ngay_le_tet', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('trang_thai', sa.String(length=15), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nhan_vien_id', 'thang', 'nam', name='uq_cham_cong')
    )
    op.create_table('khen_thuong_ky_luat',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('loai', sa.String(length=15), nullable=False),
    sa.Column('hinh_thuc', sa.String(length=150), nullable=False),
    sa.Column('ly_do', sa.Text(), nullable=False),
    sa.Column('ngay_quyet_dinh', sa.Date(), nullable=False),
    sa.Column('so_quyet_dinh', sa.String(length=50), nullable=True),
    sa.Column('cap_quyet_dinh', sa.String(length=50), nullable=True),
    sa.Column('gia_tri_thuong', sa.BigInteger(), nullable=False),
    sa.Column('thoi_han_ky_luat', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lich_su_chuc_vu',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('chuc_vu_id', sa.String(length=32), nullable=False),
    sa.Column('phong_ban_id', sa.String(length=32), nullable=True),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.Column('ly_do', sa.String(length=200), nullable=True),
    sa.Column('so_quyet_dinh', sa.String(length=50), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chuc_vu_id'], ['chuc_vu.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phong_ban_id'], ['phong_ban.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('luong',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('luong_co_ban', sa.BigInteger(), nullable=False),
    sa.Column('he_so_luong', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('phu_cap_chuc_vu', sa.BigInteger(), nullable=False),
    sa.Column('phu_cap_tham_nien', sa.BigInteger(), nullable=False),
    sa.Column('phu_cap_uu_dai', sa.BigInteger(), nullable=False),
    sa.Column('phu_cap_khu_vuc', sa.BigInteger(), nullable=False),
    sa.Column('phu_cap_khac', sa.BigInteger(), nullable=False),
    sa.Column('bhxh', sa.BigInteger(), nullable=False),
    sa.Column('bhyt', sa.BigInteger(), nullable=False),
    sa.Column('thue_tncn', sa.BigInteger(), nullable=False),
    sa.Column('khau_tru_khac', sa.BigInteger(), nullable=False),
    sa.Column('hieu_luc_tu', sa.Date(), nullable=False),
    sa.Column('hieu_luc_den', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nghi_phep',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('loai_nghi', sa.String(length=25), nullable=False),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=False),
    sa.Column('so_ngay', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('ly_do', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.String(length=15), nullable=False),
    sa.Column('ghi_chu_duyet', sa.Text(), nullable=True),
    sa.Column('ngay_duyet', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tai_khoan',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=True),
    sa.Column('ten_dang_nhap', sa.String(length=50), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=255), nullable=False),
    sa.Column('vai_tro', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ten_dang_nhap')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tai_khoan_id', sa.String(length=32), nullable=True),
    sa.Column('hanh_dong', sa.String(length=10), nullable=False),
    sa.Column('bang_du_lieu', sa.String(length=50), nullable=True),
    sa.Column('ban_ghi_id', sa.String(length=32), nullable=True),
    sa.Column('du_lieu_cu', sa.JSON(), nullable=True),
    sa.Column('du_lieu_moi', sa.JSON(), nullable=True),
    sa.Column('dia_chi_ip', sa.String(length=45), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('thoi_gian', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bao_cao',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ten_bao_cao', sa.String(length=200), nullable=False),
    sa.Column('loai_bao_cao', sa.String(length=50), nullable=False),
    sa.Column('dinh_dang', sa.String(length=5), nullable=False),
    sa.Column('tham_so', sa.JSON(), nullable=True),
    sa.Column('duong_dan_file', sa.String(length=500), nullable=True),
    sa.Column('nguoi_xuat_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_xuat_id'], ['tai_khoan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tra_luong',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nhan_vien_id', sa.String(length=32), nullable=False),
    sa.Column('luong_id', sa.String(length=32), nullable=True),
    sa.Column('cham_cong_id', sa.String(length=32), nullable=True),
    sa.Column('thang', sa.SmallInteger(), nullable=False),
    sa.Column('nam', sa.SmallInteger(), nullable=False),
    sa.Column('luong_co_ban', sa.BigInteger(), nullable=False),
    sa.Column('tong_phu_cap', sa.BigInteger(), nullable=False),
    sa.Column('thu_nhap_tang_them', sa.BigInteger(), nullable=False),
    sa.Column('thuong', sa.BigInteger(), nullable=False),
    sa.Column('tong_thu_nhap', sa.BigInteger(), nullable=False),
    sa.Column('tong_khau_tru', sa.BigInteger(), nullable=False),
    sa.Column('luong_thuc_nhan', sa.BigInteger(), nullable=False),
    sa.Column('ngay_tra_luong', sa.Date(), nullable=True),
    sa.Column('phuong_thuc', sa.String(length=20), nullable=False),
    sa.Column('so_tai_khoan', sa.String(length=30), nullable=True),
    sa.Column('ngan_hang', sa.String(length=100), nullable=True),
    sa.Column('trang_thai', sa.String(length=15), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cham_cong_id'], ['cham_cong.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['luong_id'], ['luong.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nhan_vien_id', 'thang', 'nam', name='uq_tra_luong')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tra_luong')
    op.drop_table('bao_cao')
    op.drop_table('audit_log')
    op.drop_table('tai_khoan')
    op.drop_table('nghi_phep')
    op.drop_table('luong')
    op.drop_table('lich_su_chuc_vu')
    op.drop_table('khen_thuong_ky_luat')
    op.drop_table('cham_cong')
    op.drop_table('bang_cap_chung_chi')
    op.drop_table('nhan_vien')
    op.drop_table('trinh_do')
    op.drop_table('phong_ban')
    op.drop_table('chuc_vu')
    # ### end Alembic commands ###
